Created separate page for mega menu setup
agoodmachine/agoodmachine.github.io pull request #2
Opened 2018-04-17 22:04 UTC by KyleWheel

2018-04-19 04:23 UTC, cbmunro requested changes

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +categories: navigation
maybe put this in `general`? Or we could create a `header` category if there is enough to go in there?

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +_If you haven't set up your store's Departments yet, you might want to start with the [instructions here](http://docs.agoodmachine.co/capital/departments/)_
You should be able to use relative links if you want to shorten things (also good if the base url ever changes). `/capital/departments/` should do the trick.

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +  4. Use the **Add menu item** button to add a new item. If you've set up your departments, this is where you should link to them For example, let's add an item called "Mens".
This might've already been like this, but we're missing a period between "them For".

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +  5. Choose a page that correlates to a department page that you made earlier.
I think we should maybe roll this line into the last sentence on the previous line, as it isn't really it's own step.
Something like "If you've previously created a department page titled "Mens", use "Mens" as the link title."

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +  1. Open up the Theme Editor (Online Store> Themes> Customize Theme)
Can you copy the layout [on line #11](https://github.com/agoodmachine/agoodmachine.github.io/pull/2/files#diff-77b033b7a7d6bfb99aac0addfa8e747fR11) for these arrow things.

2018-04-19 04:23 UTC, cbmunro commented on _capital/mega-menus.md
> +  3. Select 'Add mega menu' underneath the Content heading, close to the bottom of the settings area.
Let's always use double quotes.

2018-04-23 22:41 UTC, KyleWheel commented on _capital/mega-menus.md
> +categories: navigation
Yeah, header makes more sense

2018-04-25 21:15 UTC, merged